// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khrvmlegzzbqmfrkashk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtocnZtbGVnenpicW1mcmthc2hrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzNDkyOTYsImV4cCI6MjA3NzkyNTI5Nn0.rPdYJxjMUDGvNKJrfEK2yeaLG2pHUGSt_VOrE9iTGqM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});